# WTK
MIDP2/midp=C:\\WTK2.5.2_01
ant.home=D:\\programs\\j2me\\apache-ant-1.7.0

# config is "jimm", "mrim", "jabber" or "multi"
config=multi

# release, test, test2
builds_list=Midp2d
#builds_list=DefaultFull,Siemens1full,Midp2nfd,Midp2d,Siemens2d,Motorolad,Midp2ani,Midp2nfani,Siemens2ani,Motorolaani,Midp2full,MotorolaFull,Siemens2,Midp2nf

#skip-obfuscate=true

build_name=Midp2